### ISSUE TITLE
Propagate HTTP status codes

### ISSUE THREAD

**Issue by gengjiawen** [AEB-labs/graphql-weaver#14]
I run into some issue on production enviroment.
* I use nginx as  reverse proxy, sometimes I got 502 error.
* How to handle error. Such as if one schema request return 401 if token expire, another schema request is 500, in those circumstances, how to return to the proper merged shema response status. Maybe this is related to the first question.

**Comment by Yogu** [comment]
I assume your nginx reverse proxy is used as one endpoint in a weaver config. In grpahql-weaver, the `GraphQLClient` instance assigned to an endpoint config (`client` property) is responsible of handling all the HTTP stuff. If you specify the `url` property, the default `HttpGraphQLClient` implementation will be used. If the status code is not 200, it determines whether the response is still a valid GraphQL response (a JSON object with an `errors` property). If that's the case, it is handled as if the status was 200 with these error messages. If not, it throws a generic exception with the status code.

graphql-weaver currently fails a whole query as soon as one requested endpoint reported an error. This is something we intend to improve in the near future, so that the successful endpoints are still included successfully in the result.

A GraphQLSchema can only report GraphQL errors - the same applies for a woven schema. Which HTTP status code you set is determined by the server implementation. If you can configure/contorl the server implementation, it's up to you to send whichever exit code you like.

Did this information help?

**Comment by gengjiawen** [comment]
For now, how can I get the right response code ?
If I pass a expired token, the response code is still 200. The 401 error is in the body like this
```json
{
  "errors": [
    {
      "message": "GraphQL endpoint at http://web/queries reported 401 Unauthorized",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createTaxiDriver"
      ]
    }
  ],
  "data": {
    "createTaxiDriver": null
  }
}
```

**Comment by Yogu** [comment]
@gengjiawen It looks like you deleted your comment, did you solve the problem already? This is was i was going to reply:

There is no straightforward answer because firstly this depends on the graphql server implementation you use and secondly you need to decide how to combine the different HTTP response statuses different endpoints reported. But as a guideline, I would suggest that you change or configure your graphlql server implementation (I don't know which one you use) so that it

* looks into the `errors` part of the response and filters the error messages for a regex `/GraphQL endpoint at ([^\s]+) reported ([0-9]+) .+/`
* settles on one status code using the matches (in case there are multiple errors with status codes)
* uses this status code

**Comment by gengjiawen** [comment]
No, I have not solve it. I deleted it because I have not figure out a few questions. Thanks for the replay, I will give it a try. For now I run into a problem, the status code from Query is 500 and Mutation 200 if I pass the wrong token.
query request:
```
query {
  viewer {
    id
  }
}
```
query res (status code is 500):
```
{
  "errors": [
    {
      "message": "GraphQL error: You are not authorized to perform that action.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "viewer"
      ]
    }
  ],
  "data": null
}
```
Is [graphql-express](https://github.com/graphql/express-graphql/blob/master/src/index.js#L297) causing this, since data is null ?

**Comment by Yogu** [comment]
> Is [graphql-express](https://github.com/graphql/express-graphql/blob/master/src/index.js#L297) causing this, since data is null ?

Looks like it.

[apollo-server](https://github.com/apollographql/apollo-server) has an option `formatResponse` which should be what you are looking for. Another approach would be to add some middleware after graphql-express, see [some of these suggestions](https://github.com/graphql/express-graphql/issues/279).

**Comment by gengjiawen** [comment]
Thanks. Actually, my first thought to fix the status code is to write a express middleware to hijack the status code. But for now, I have not got any progress, mainly I don't want 500 as a status code using `graphql-express`. I will try to switch to `apollo-server` to see can they have a way to fix the forward header.

**Comment by gengjiawen** [comment]
By the way, the 502 problem seems like a issue I caused, because I use `setInterval` to check schema update, when I have found new shema, I use nodemon to restart my server. I deleted those code, and the problem goes away. Not quite sure what causing this.

**Comment by Yogu** [comment]
Glad you're making progress. Just a side note: You don't need to restart the whole `node` process when the schema changes, you can just call `weaveSchemas` again and store the new schema, like this:

```typescript
async function startServer() {
  let currentSchema = await createSchema();

  const app = express();

  app.use('/graphql', bodyParser.json(), 
    graphqlExpress(req => {
      return ({
        schema: currentSchema ,
        context: req
      });
    })
  );

  app.listen(PORT);

  // or something fancier to detect changes
  setInterval(async function() {
    currentSchema = await createSchema()
  }, 10000);
}

async function createSchema() {
  return weaveSchemas(/* ... */)
}
```

**Comment by gengjiawen** [comment]
The refresh solution you provided is valid, thanks. I also have some progress on handle status code.

**Comment by gengjiawen** [comment]
In handle the status code, I run into some issue. In order to return the status code I want, I did something like this
```js
  const app = new koa();
  const router = new koaRouter();
  app.use(async (ctx, next) => {
    try {
      await next();
    } catch (err) {
      ctx.response.status = err.statusCode || err.status || 500;
      ctx.response.body = {
        message: err.message
      };
    }
  });

  // koaBody is needed just for POST.
  router.post('/graphql', koaBody(),
    (ctx, next) => {
      console.log("m1 start");
      console.log(ctx.request);
      next();
      console.log(ctx.response);
      console.log(ctx.body);
      console.log("m1 end");
    }
    ,graphqlKoa(req => {
      return ({
        schema: currentSchema,
        context: req
      });
    }));

  router.get('/graphiql', graphiqlKoa({endpointURL: '/graphql'}));
```
But I can't catch the below error. Any thing I can do to catch the error ?
```
TraceError: GraphQL error: You are not authorized to perform that action.
    at TraceError.Exception (/graphql-gateway/node_modules/trace-error/dist/Exception.js:82:17)
    at new TraceError (/graphql-gateway/node_modules/trace-error/dist/TraceError.js:173:84)
    at Object.assertSuccessfulResult (/graphql-gateway/node_modules/graphql-weaver/src/graphql/execution-result.ts:9:19)
    at ResolverTransformer.<anonymous> (/graphql-gateway/node_modules/graphql-weaver/src/pipeline/proxy-resolvers.ts:58:30)
    at step (/graphql-gateway/node_modules/graphql-weaver/dist/src/pipeline/proxy-resolvers.js:40:23)
    at Object.next (/graphql-gateway/node_modules/graphql-weaver/dist/src/pipeline/proxy-resolvers.js:21:53)
    at fulfilled (/graphql-gateway/node_modules/graphql-weaver/dist/src/pipeline/proxy-resolvers.js:12:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    {
      "message": "You are not authorized to perform that action.",
      "status": "401"
    }
```

**Comment by Yogu** [comment]
Ah, I guess the endpoint still serves a valid GraphQL response where `errors` is populated. In this case, you won't even get the status code in the error message because we just pass through the errors. In the current version, you get an ugly `TraceError`, but in the upcoming version 0.11, the response will transparently include the errors at their right positions.

For your use case, this means that you probably don't even want to throw an error within the `GraphQLClient`. Instead, I'd suggest to collect the status codes in the GraphQL context. The context is determined by the graphql server and it gets passed around to all clients. In your case it's the request.

You could try something like this:

```typescript
class CustomHttpGraphQLClient implements GraphQLClient {
    protected async fetchResponse(document: DocumentNode, variables?: { [name: string]: any }, context?: any, introspect?: boolean): Promise<Response> {
        const response = await this.fetch(await this.getRequest(document, variables, context, introspect));
        if (!response.ok) {
            context.endpointStatusCode = res.status;
        }
        return response;
    }
}

const currentSchema = weaveSchemas({
    endpoints: [{
        client: new CustomHttpGraphQLClient('url...')
    }]
});

  const app = new koa();
  const router = new koaRouter();
  app.use(async (ctx, next) => {
    await next(); // graphql execution
    if (ctx.request.endpointStatusCode) {
      ctx.response.status = ctx.request.endpointStatusCode;
    }
  });

  // koaBody is needed just for POST.
  router.post('/graphql', koaBody(),
    (ctx, next) => {
      console.log("m1 start");
      console.log(ctx.request);
      next();
      console.log(ctx.response);
      console.log(ctx.body);
      console.log("m1 end");
    }
    ,graphqlKoa(req => {
      return ({
        schema: currentSchema,
        context: req
      });
    }));

  router.get('/graphiql', graphiqlKoa({endpointURL: '/graphql'}));
```

**Comment by gengjiawen** [comment]
I run into this error, index.ts (53,21): Property 'endpointStatusCode' does not exist on type 'Request'. Looks like need any way to pass.
The context in koa defines like this :
```ts
    interface Context extends BaseContext {
        app: Application;
        request: Request;
        response: Response;
        req: IncomingMessage;
        res: ServerResponse;
        originalUrl: string;
        cookies: Cookies;
        accept: accepts.Accepts;
        state: any;
        /**
         * To bypass Koa's built-in response handling, you may explicitly set `ctx.respond = false;`
         */
        respond?: boolean;
    }
```

**Comment by gengjiawen** [comment]
ha, I have an idea. The Context state looks something I can hook into.

**Comment by gengjiawen** [comment]
Solved by something like this:
```ts
  protected async fetchResponse(document: DocumentNode, variables?: { [name: string]: any }, context?: any, introspect?: boolean): Promise<Response> {
    const response = await super.fetchResponse(document, variables, context, introspect);
    if (!response.ok) {
      context.state = {raw: response};
    }
    return response;
  }
```
```ts
  app.use(async (ctx, next) => {
    console.log('me start');
    await next(); // graphql execution
    if (ctx.state.raw !== undefined) {
      const raw: Response = ctx.state.raw;
      console.log(raw.status);
      ctx.status = raw.status;
      ctx.body = raw.body;
    }
    console.log('me end');
  });
```

**Comment by gengjiawen** [comment]
Thanks for your great patience and help. I believe all my problem has been resolved :)
