### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by gengjiawen** [AEB-labs/graphql-weaver#4]
* weaveSchemas is exposed as createProxySchema
* createProxySchema return promise, should use await to get schema.

**Comment by Yogu** [comment]
Thanks for your feedback, @gengjiawen!

`weaveSchemas` is exposed as `createProxySchema` for compatibility reasons (we are still using this tool internal, and it used to be called that way). Due to my mistake when publishing, the new `weaveSchemas` has not been exposed in version 0.9.1. I fixed it in 0.9.2.

I fixed the part about promises in the README.
